version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/git/SooloChat/

permissions:
  - object: /home/ubuntu/app/git/SooloChat/
    owner: ubuntu
    group: ubuntu
hooks:
   AfterInstall:
     - location: /deploy.sh